contact_links:
  - name: ğŸ¤· Phileas Community Forum
    url: https://community.philterd.ai/
    about: Ask and answer Phileas usage questions here.
  - name: ğŸ” Report a Security Issue
    url: https://github.com/philterd/.github/blob/main/security.md
    about: Please e-mail security@philterd.ai. Do not create a public GitHub issue.